### ISSUE TITLE
Add ability to track live price of members in main voice chat channel

### ISSUE THREAD

**Issue by Path-A** [ogxt/DestinyMarketTracker#10]
Recommended by [/u/Official_Zach](https://www.reddit.com/r/Destiny/comments/ywseun/i_updated_a_chart_that_tracks_destinygg_orbiters/iwl5fry/):

Discord API docs for voice channel [changed member state](https://discord.js.org/#/docs/discord.js/main/class/Client?scrollTo=e-voiceStateUpdate) and a [get members](https://discord.js.org/#/docs/discord.js/main/class/VoiceChannel?scrollTo=members).

**Comment by ogxt** [comment]
Thanks to jelmer its been in the works for a day or so plan on adding it soon
